name: dmelon-docs
channels:
  - conda-forge
dependencies:
    - numpy
    - scipy
    - xarray
    - eofs
    - cartopy
    - matplotlib
    - dask
    - netCDF4
    - bottleneck
    - coverage
    - numpydoc
    - sphinx
    - sphinx-book-theme
    - sphinx-copybutton
    - myst-parser
    - myst-nb
    - sphinxcontrib-srclinks
