name: Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run:
    name: Build (${{ matrix.python-version }} | ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: conda-py${{ matrix.python-version }}-dmelon
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          channel-priority: strict
          mamba-version: "*"
          activate-environment: dmelon-env
          python-version: ${{ matrix.python-version }}
          use-only-tar-bz2: true
      - name: Install dependencies Python ${{ matrix.python-version }}
        run: |
          mamba install --yes --file requirements.txt --file requirements-dev.txt
      - name: Install the Package
        run: |
          python -m pip install -e . --no-deps --force-reinstall
      - name: Version info
        run: |
          conda info -a
          conda list
      - name: Run tests
        run: |
          pytest --cov=./ --cov-report=xml
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
